# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WatchStream' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WatchStream


end

target 'WatchStream WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WatchStream WatchKit App

end

target 'WatchStream WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'FirebaseAuth'
  pod 'Firebase/Database'
  

end
